services:
  # MongoDB service
  mongodb:
    image: mongo:6
    container_name: zeztra-mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    environment:
      - MONGO_INITDB_DATABASE=zeztra
    restart: unless-stopped

  # Backend service with hot reloading
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: zeztra-backend-dev
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/zeztra
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: yarn dev
    restart: unless-stopped

  # Frontend service with hot reloading
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: zeztra-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn dev
    restart: unless-stopped

volumes:
  mongodb_data_dev:
    driver: local